### ISSUE TITLE
New Transaction status for unexpected behaviour

### ISSUE THREAD

**Issue by Pascal-Thiel** [Entwicklung-AvaL-Standard/aval-api-spec#25]
### What?
We have implemented a new status "-1" to tell our Partner that we encountered an unexpected behaviour and can no longer sync the transaction between our systems. The status is an unrecoverable End-status. We won´t sent or aceppt any further updates regarding the transaction.

### Why?
We chose to do so for two reasons.

First the default AVAL-Flow does not allow any further notifications sent by the client to the supplier after sending status 1 (Beauftragt Instructed). In Case of any issue on the client-site they are not allowed to inform the supplier about the issue in an automated way. In one case the suplier started a transaction in status 7 (Avisiert planned). Our accpeted the Tranaction but could not sent it to our backend system. Because this communication is asynchonous we are by default not allowed to inform the suplier about the issue. With the new -1 status we informed the Partner that we can not accept any further updates regarding this transcation.

Second we thought that our Departments should always be able to cancel any automated process in case of emergency. So the -1 status can also be seen as an emergency switch to stop any further communication. This might happen when there are issues between both partner that must be resolved in an manual way.  The Cancelation by status 6 would not be sufficient because we expect that the Cancelation-status implies that the customer don´t want the Transaction anymore. The -1 status only stops the synchronization without preventing our Departments to manually fulfill the Transaction for customers by manually communicating with the AVAL-Partner.

### How?
We propose to implement the -1 status in the AVAL-Prozess. The status can be sent by both Partners. The status can only be sent to existing and not completed Transactions. Not Completed are Transactions within the statuss

- 1 (Beauftragung Instructed)
- 2 (Technisch akzeptiert Technically accepted)
- 4 (Fachlich akzeptiert reviewed)
- 7 (Avisiert planned)
- 8 (Leistung erbracht accomplished)

The corresponding JSON-Body could look something like this:
```
{
    "id": "#TRANSACTION_ID#",
    "status": -1,
    "avalId": "#MATCHING_ID#"
}
```

We could think about an information field in case that the sending system is able to give further information about the synchonization-stop.

**Comment by curban111** [comment]
I support the idea of establishing a termination condition for the sync between the partners. This is particularly useful for asynchronous processing, where HTTP status codes cannot be used.

The negative value '-1' used is not compatible with today's AvaL OpenAPI specification. Because this defines that the transaction status should be implemented as an integer with a smallest value of '1' and a largest value of '10'. This means that the specification has to be adjusted, because new positive values are also not possible with the current specification.

**Comment by TristanKuesters** [comment]
I also support this idea.
