### ISSUE TITLE
requiredDocuments attribute in Aval2Matching should be array of string

### ISSUE THREAD

**Issue by jmichler** [Entwicklung-AvaL-Standard/aval-api-spec#30]
In 
https://github.com/Entwicklung-AvaL-Standard/aval-api-spec/blob/a4811f94e178bd722b303b53320fbc7359e28bb0/AVAL-Spec.yml#L495

the type of the array-elements should be string to be consistent with https://github.com/Entwicklung-AvaL-Standard/aval-api-spec/blob/a4811f94e178bd722b303b53320fbc7359e28bb0/AVAL-Spec.yml#L295

The "integer" there has been introduced before the introduction of a formal "catalog entry" for the document formats

**Comment by jmichler** [comment]
@curban111 @TristanKuesters @hwilleke gibt es außer Tegos und uns noch jemanden der diese AvaL2-Matchings überhaupt nutzt? Wenn nicht würde ich sagen wir mergen den Merge-Request, oder?

**Comment by curban111** [comment]
Projekt 8 (siehe [avalstandard.de](https://www.avalstandard.de/der-standard/aval-life)) ist für Ende Q1 avisiert. Ich denke @SiegfriedVogel sollte hierfür noch sein OK geben.

--

Project 8 (see  [avalstandard.de](https://www.avalstandard.de/der-standard/aval-life)) is announced for the end of the first quarter. I think @SiegfriedVogel should also give his OK for this.
