### ISSUE TITLE
New attribute in Aval2Matching "requiredDeviationDocuments" to defined required documents in case of state 10 (Rückmeldung mit Abweichung)

### ISSUE THREAD

**Issue by jmichler** [Entwicklung-AvaL-Standard/aval-api-spec#32]
Currently AvaL2 defines which document types are allowed and required for "regular cases" (Rückmeldung, state 9) in the field "requiredDocuments". However it is often required to define a different set of document applicable in irregular cases; e.g. normally no Wiegeschein/Leistungsschein ist required however if it was not possible to get a callibrated weighing, then some more documents are necessary.
I'd suggest to add another field requiredDeviationDocuments into the AvaL2-Matching that controls which documents need to be transferred before a "state 10" can be sent; similar as requiredDocuments does for "regular" state 9 messages.

**Comment by curban111** [comment]
I consider it a challenge to control or block the process flow with this change. If we do it that way, the documentation will definitely have to be adjusted. We should also check whether the error codes need to be expanded or appropriately documented when patching a transaction.

**Comment by jmichler** [comment]
> I consider it a challenge to control or block the process flow with this change. If we do it that way, the documentation will definitely have to be adjusted. 

yes I agree, however in my opinion the only alternatives would be to either "enforce async waiting for 'some' time or putting the workflow control behind the transfer of documents which I consider "more ugly".

> We should also check whether the error codes need to be expanded or appropriately documented when patching a transaction.

I would think that this would still work as 405 "illegal state transition" but we should definitely update the description of that error as well as the PDF document that as of today only states "documents can be transferred at any time. I think we could still allow this as long as we make clear that "unsolicited" documents need to be agreed upon in a bilateral way if exchanged after the aval transaction has reached an "end state".

**Comment by curban111** [comment]
> yes I agree, however in my opinion the only alternatives would be to either "enforce async waiting for 'some' time or putting the workflow control behind the transfer of documents which I consider "more ugly".

Reasonable arguments, so let's accept the proposed implementation.

> I would think that this would still work as 405 "illegal state transition" but we should definitely update the description of that error as well as the PDF document that as of today only states "documents can be transferred at any time. I think we could still allow this as long as we make clear that "unsolicited" documents need to be agreed upon in a bilateral way if exchanged after the aval transaction has reached an "end state".

The 405 seems to suits well. We will describe the usage especially in cases where documents will be send after an "end state" in the documentation on the www.avalstandard.de homepage.
