### ISSUE TITLE
Missing additional property value while tranfering Extended Information independently

### ISSUE THREAD

**Issue by curban111** [Entwicklung-AvaL-Standard/aval-api-spec#34]
Unfortunately, the specification on how to transfer ExtendendInformation without transaction or matching updates does not contain the additionalProperties key.

While sending extended information during a transaction or matching update via  **_/aval2matchings/{avalId_}** you are able to send information in the following form:

`"extendedInformation": {
    "additionalProp1": {
      "type": "Behälternummer",
      "content": "A 123 987 456"
    },
    "additionalProp2": {
      "type": "Behälternummer",
      "content": "A 123 987 456"
    }...
  }`

But if you sending extended information idenpendently via **_/avalmatchings/{avalId}/extendedInformation_** you could only send information the following way:

`{
  "type": "Behälternummer",
  "content": "A 123 987 456"
}`

As written in the technical concept (https://www.avalstandard.de/files/content/downloads/aval-standard-teil-4-webservices/AvaL_Projekt_1_Technisches_Konzept_V1.5.pdf - chapter 4.1) the key may be freely chosen. However, if an API uses this key internally, then the key must also be able to be passed in the case of independent transfer.

It would be very helpful if this missing additionalProperties key could also be passed here.

**Comment by Pascal-Thiel** [comment]
Sending extended information should always work in the same way. It is difficult to understand why the extendedInformation request without matching or transaction does not have the additionalProp-Key.
I support the Request for change. The .../extendedInformation-Request should look like the Request with matching or transaction:
`{ "additionalProp1": { "type": "Behälternummer", "content": "A 123 987 456" }, "additionalProp2": { "type": "Behälternummer", "content": "A 123 987 456" },... }`
