### ISSUE TITLE
Use of the European definition of the AVV term

### ISSUE THREAD

**Issue by curban111** [Entwicklung-AvaL-Standard/aval-api-spec#42]
In Germany the "European Waste Catalouge" (EWC) was implemented by the "Abfallverzeichnis-Verordnung" (AVV). Therefore, in terms of the internationalization of the AvaL Standard, it would make more sense to use “EWC” instead of “AVV” in the “Aval2Matching” entity.

**Comment by jmichler** [comment]
@curban111 I only saw this right now.
I would strongly suggest to not do this / to revert this: this is a breaking change that makes it impossible for users of the previous version to speak with the new version. In my opinion this is not worth it and should not be done without a clear communication on timeline.

I think we should discuss this at the regular developer meeting.

**Comment by curban111** [comment]
Hello @jmichler , I'm usually completely on your side. However, the attribute was only introduced last Friday and so the likelihood of it already being implemented seemed very low. Have you already implemented it?

**Comment by jmichler** [comment]
Hi

I've missed that addition (was there a MR/issue for that?).

Indeed then the renaming is not critical.

And adding the attribute shouldn't harm as long as it is a purely optional attribute which it seems to be.


I somehow had in my head that the avv number was already there - sorry about that.

Regards

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by curban111** [comment]
The associated issue was #39 and the MR was #41 (and not #43 as previously mentioned). And as you said, it is an optional attribute, so we did the renaming this way as an exception.

You weren't the only one who assumed that the AVV / EWC had already been implemented. No apology necessary. So I will close this issue.
